#!/bin/sh
fecha=$(date "+%Y-%m-%d")
fecha2=$(date "+%H-%M-%S")
ruta="/home/vagrant/backups"
if [ ! -d /home/vagrant/backups ]
then
      mkdir /home/vagrant/backups
fi
tar -cvf $ruta/copia_incremental'_'$fecha'_'$fecha2".tar.gz" -g $ruta/incremental.st --absolute-names $ruta/incremental.st /var/www/html/*
