#!/bin/sh

rsync -avz -e "ssh -i /vagrant/.vagrant/machines/lan/virtualbox/private_key" /home/vagrant/backups/copia* vagrant@192.168.120.2:/home/vagrant/
rsync -avz -e "ssh -i /vagrant/.vagrant/machines/lan/virtualbox/private_key" /home/vagrant/backups/incremental.st vagrant@192.168.120.2:/home/vagrant/
rsync -avz -e "ssh -i /vagrant/.vagrant/machines/lan/virtualbox/private_key" /home/vagrant/backups/total.st vagrant@192.168.120.2:/home/vagrant/
rsync -avz -e "ssh -i /vagrant/.vagrant/machines/lan/virtualbox/private_key" /home/vagrant/backups/diferencial.st vagrant@192.168.120.2:/home/vagrant/
